# Generated by Django 3.0 on 2020-01-11 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=150)),
                ('outstanding', models.IntegerField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('invoice_pic', models.ImageField(default='Not present', upload_to='invoice/images')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devalappers.Customer')),
            ],
        ),
    ]
