# Generated by Django 3.0 on 2020-01-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devalappers', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
