# Generated by Django 3.0 on 2020-01-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devalappers', '0006_order_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
