# Generated by Django 3.0 on 2020-01-12 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devalappers', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
