# Generated by Django 3.0 on 2020-01-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='invoice_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
