# Generated by Django 3.0 on 2020-01-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trial', '0002_auto_20200115_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
